export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const LOAD_CURRENT_SERVICE = "LOAD_CURRENT_SERVICE";
export const FETCH_SERVICES = "FETCH_SERVICES";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const ADD_SERVICE = "ADD_SERVICE";

export const FETCH_STAFFS = "FETCH_STAFFS";
export const DEMOTE_STAFFS = "DEMOTE_STAFFS";

export const FETCH_ADMIN = "FETCH_ADMIN";
export const DEMOTE_ADMIN = "DEMOTE_ADMIN";
export const FETCH_APPOINTMENT = "FETCH_APPOINTMENT";
export const FETCH_USER_APPOINTMENTS = "FETCH_USER_APPOINTMENTS";
