export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const LOAD_CURRENT_SERVICE = "LOAD_CURRENT_SERVICE";
export const FETCH_SERVICES = "FETCH_SERVICES";
